### ISSUE TITLE
Tag HEAD of 'develop' with '1.0-filter-message'

### ISSUE THREAD

**Issue by aegilops** [advanced-security/filter-sarif#3]
Please can we tag the HEAD of the `develop` branch with `1.0-filter-message`, or something similar?

I'd like to point users at this feature, before it's merged to `main`, but don't want to just use `develop` since that might change to include a different new feature (in theory!).

@zbazztian

**Comment by zbazztian** [comment]
@aegilops The tags [v1](https://github.com/advanced-security/filter-sarif/releases/tag/v1) and [v1.0](https://github.com/advanced-security/filter-sarif/releases/tag/v1.0) both point to the head of develop. Do those work for you or is a more descriptive one required?

**Comment by aegilops** [comment]
The goal was to let people directly use the feature with a tag, but 1.0 on develop is fine.

I hope we can merge to main soon enough after you've checked the tests and maybe after we've done some perf testing?
