### ISSUE TITLE
v1 Tag Usage Not Working

### ISSUE THREAD

**Issue by ahernandez411** [advanced-security/filter-sarif#8]
When I attempt to use `filter-sarif` in my workflow with the `v1` tag it fails with an error: `TypeError: 'type' object is not subscriptable.`

I did some investigation and this is due to the `globber.py -> _match_components` function due to the `list[str]` usage. I see in the `develop` branch this has been fixed, [here](https://github.com/advanced-security/filter-sarif/blob/develop/globber.py#L46), with the addition of the typing import and code change as well.

Are there any plans to create a new tag that works? For now I am just referencing the `main`  branch's latest commit SHA.

**Comment by aegilops** [comment]
I've just added a new release, `v1.0.1`, and altered the tags `v1` and `v1.0` to point there.

That should resolve this. I will work on merging the work in `develop` to `main` and release `v1.1`, which will override the `v1` tag too.
